### ISSUE TITLE
ROS: Install ROS on PC

### ISSUE THREAD

**Issue by AksonovSergei** [AksonovSergei/kpi_rover_ros_sw#1]
Ми будемо використовувати матеріали наступного проекту:
https://articulatedrobotics.xyz/category/getting-ready-to-build-a-ros-robot

Будьска однайомтесь з розділами:
[What do you need?](https://articulatedrobotics.xyz/tutorials/ready-for-ros/what-you-need-for-ros)
[Networking](https://articulatedrobotics.xyz/tutorials/ready-for-ros/networking)
[Installing ROS](https://articulatedrobotics.xyz/tutorials/ready-for-ros/installing-ros)
[ROS Overview](https://articulatedrobotics.xyz/tutorials/ready-for-ros/ros-overview)

Зверніть увагу що в цих матеріалах використовувається не остання версія ROS2. Ми маємо використовувати останню:
https://docs.ros.org/en/jazzy/index.html

Очікуваний результат: Остання версія ROS2 встановленна на вашему компьюторі.

**Comment by Fastroof** [comment]
ROS2 найновішої версії завантажений на ubuntu 24.04. Перевірено демо.
![Screenshot from 2024-07-05 15-24-16](https://github.com/AksonovSergei/kpi_rover_ros_sw/assets/50989762/f16f48fd-d731-4a1a-90ed-8573aef067f0)
![Screenshot from 2024-07-05 13-09-00](https://github.com/AksonovSergei/kpi_rover_ros_sw/assets/50989762/0b03856e-4952-446a-9059-4082bdd8ce15)

**Comment by AksonovSergei** [comment]
Це супер. Дуже вдячний. Продовжуй вивчати цей туторіал.

https://articulatedrobotics.xyz/tutorials/ready-for-ros/packages
https://articulatedrobotics.xyz/tutorials/ready-for-ros/tf
https://articulatedrobotics.xyz/tutorials/ready-for-ros/urdf
https://articulatedrobotics.xyz/tutorials/ready-for-ros/gazebo

**Comment by AksonovSergei** [comment]
Я гадаю ми можемо закрити цю задачу.
